config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey.urls')),
]

survey/urls.py
from django.urls import path
from . import views

app_name = 'survey'
urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('grade1/', views.Grade1View.as_view(), name='grade1'),
    path('grade2/', views.Grade2View.as_view(), name='grade2'),
    path('grade3/', views.Grade3View.as_view(), name='grade3'),
    path('小学1年生/', views.Question1View.as_view(), name='小学1年生'),
    path('小学2年生/', views.Question2View.as_view(), name='小学2年生'),
    path('小学3年生/', views.Question3View.as_view(), name='小学3年生'),
    # path('result/', views.ResultView.as_view(), name='result'),
]

survey/models.py
from django.db import models

# class Grade(models.Model):
#     name = models.CharField(verbose_name='学年', max_length=10)
    
#     class Meta:
#         verbose_name_plural = "学年"

#     def __str__(self):
#         return self.name


# class Questions(models.Model):
#     grade = models.ForeignKey(Grade, verbose_name='学年', related_name='q_grade', on_delete=models.CASCADE)
#     text = models.CharField(verbose_name='問題', max_length=20)
#     ans = models.CharField(verbose_name='正解', max_length=10)
    
#     class Meta:
#         verbose_name_plural = "問題"

#     def __str__(self):
#         return self.text

# class Answers(models.Model):
#     question = models.ForeignKey(Questions, verbose_name='問題番号', related_name='ans_q', on_delete=models.CASCADE)
#     ans_num = models.IntegerField(verbose_name="回答番号")
#     name = models.CharField(verbose_name='回答', max_length=10)
    
#     class Meta:
#         verbose_name_plural = "回答"

#     def __str__(self):
#         return self.name

survey/forms.py
import os
from django import forms
from .models import 


class InquiryForm(forms.Form):
    CHOICE = [
        ( 'アプリについて', 'アプリについて'),
        ( '商品について', '商品について'),
        ( 'その他について', 'その他について'),
    ]

    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.ChoiceField(label='お問い合わせの種類', widget=forms.Select, choices= CHOICE, initial=0)
    message = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class']='form-control'
        self.fields['name'].widget.attrs['placeholder']='山田 太郎'

        self.fields['email'].widget.attrs['class']='form-control'
        self.fields['email'].widget.attrs['placeholder']='xxx@email.com'

        self.fields['title'].widget.attrs['class']='form-control'

        self.fields['message'].widget.attrs['class']='form-control'
        self.fields['message'].widget.attrs['rows']='3'



class PersonalForm(forms.ModelForm):
    class Meta:
        model = Sample

        fields = ('gender', 'img')

        widgets = {
            'gender':forms.RadioSelect
        }

survey/views.py
from asyncio.log import logger
import logging
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.views import generic
# from .models import Grade, Questions
from config.settings import *
from django.urls import reverse
from urllib.parse import urlencode

logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "index.html"


class Grade1View(generic.TemplateView):
    template_name = "grade1.html"


class Grade2View(generic.TemplateView):
    template_name = "grade2.html"


class Grade3View(generic.TemplateView):
    template_name = "grade3.html"


class Question1View(generic.TemplateView):
    template_name = "questions.html"


class Question2View(generic.TemplateView):
    template_name = "questions.html"


class Question3View(generic.TemplateView):
    template_name = "questions.html"


# class ResultView(generic.ListView):
#     template_name = "result.html"
#     def get(self, request):
#         base = request.GET.get('base')
#         gender = request.GET.get('gender')
#         #URLからbase取得
#         context = {}
#         context["base"] = Base_type.objects.filter(id=base).first()
#         context["colors"] = Colors.objects.filter(base_type=base)
#         if int(gender) <= 2:
#             context["items"] = Items.objects.filter(color__base_type__id=base, gender=gender)
#         else:
#             context["items"] = Items.objects.filter(color__base_type__id=base).all()
        
#         return render(request, 'result.html', context)

survey/templates/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/ress.css' %}">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

    <!-- font -->
    <script>
        (function(d) {
          var config = {
            kitId: 'mvu8gqv',
            scriptTimeout: 3000,
            async: true
          },
          h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
        })(document);
    </script>

    <title>けいさんもんだい｜小学生の算数演習</title>
</head>
<body>
    <div class="top d-flex">
        <!-- 共通部分 -->
        <nav class="g-nav">
            <div class="logo">
                <a href="{% url 'survey:index' %}">
                    <img src="{% static 'img/logo.png' %}" alt="ロゴ" class="nav-logo">
                </a>
            </div>
            <ul>
                <li tabindex="1" class="grade">
                    <a href="{% url 'survey:grade1' %}">小学1年生</a>
                </li>
                <li tabindex="2" class="grade">
                    <a href="{% url 'survey:grade2' %}">小学2年生</a>
                </li>
                <li tabindex="3" class="grade grade3">
                    <a href="{% url 'survey:grade3' %}">小学3年生</a>
                </li> 
            </ul>
        </nav> <!-- 共通部分 -->
        {% block contents %}{% endblock %}

    </div>    
</body>
</html>

survey/templates/grade1.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
    <main class="top-page">
        <h1 class="page-ttl d-flex">小学<span class="yellow d-flex">1</span>年生</h1>
        <div class="main-txt d-flex">
            <p>
                ぜんぶで10問！<br>
                キミはどれくらいできるかにゃ？
            </p>
        </div>
        <div class="left-cloud-start d-flex">
            <img src="{% static 'img/leftCloud.png' %}" alt="雲">
        </div>
        <div class="right-cloud-start d-flex">
            <img src="{% static 'img/rightCloud.png' %}" alt="雲">
        </div>
        <div class="addition yurayura">
            <img src="{% static 'img/addition.png' %}" alt="">
        </div>
        <div class="subtraction yurayura">
            <img src="{% static 'img/subtraction.png' %}" alt="">
        </div>
        <div class ="multiplication fuwafuwa">
            <img src="{% static 'img/multiplication.png' %}" alt="">
        </div>
        <div class="division fuwafuwa">
            <img src="{% static 'img/division.png' %}" alt="">
        </div>
        <div class="start-cat">
            <img src="{% static 'img/cat_start.png' %}" alt="ボタン上の猫">
        </div>
        <div class="start-btn d-flex">
        <a href="" class="btn btn--start btn--radius">はじめる！！</a>
        </div>
        <div class="bottom-cloud">
            <img src="{% static 'img/bottomCloud.png' %}" alt="雲">
        </div>
    </main>
{% endblock %}

survey/templates/grade2.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

    <main class="top-page">
        <h1 class="page-ttl d-flex">小学<span class="yellow d-flex">2
        </span>年生</h1>
        <div class="main-txt d-flex">
            <p>
                ぜんぶで10問！<br>
                キミはどれくらいできるかにゃ？
            </p>
        </div>
        <div class="left-cloud-start d-flex">
            <img src="{% static 'img/leftCloud.png' %}" alt="雲">
        </div>
        <div class="right-cloud-start d-flex">
            <img src="{% static 'img/rightCloud.png' %}" alt="雲">
        </div>
        <div class="addition yurayura">
            <img src="{% static 'img/addition.png' %}" alt="">
        </div>
        <div class="subtraction yurayura">
            <img src="{% static 'img/subtraction.png' %}" alt="">
        </div>
        <div class ="multiplication fuwafuwa">
            <img src="{% static 'img/multiplication.png' %}" alt="">
        </div>
        <div class="division fuwafuwa">
            <img src="{% static 'img/division.png' %}" alt="">
        </div>
        <div class="start-cat">
            <img src="{% static 'img/cat_start.png' %}" alt="ボタン上の猫">
        </div>
        <div class="start-btn d-flex">
        <a href="" class="btn btn--start btn--radius">はじめる！！</a>
        </div>
        <div class="bottom-cloud">
            <img src="{% static 'img/bottomCloud.png' %}" alt="雲">
        </div>
    </main>
{% endblock %}

survey/templates/grade3.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

    <main class="top-page">
        <h1 class="page-ttl d-flex">小学<span class="yellow d-flex">3</span>年生</h1>
        <div class="main-txt d-flex">
            <p>
                ぜんぶで10問！<br>
                キミはどれくらいできるかにゃ？
            </p>
        </div>
        <div class="left-cloud-start d-flex">
            <img src="{% static 'img/leftCloud.png' %}" alt="雲">
        </div>
        <div class="right-cloud-start d-flex">
            <img src="{% static 'img/rightCloud.png' %}" alt="雲">
        </div>
        <div class="addition yurayura">
            <img src="{% static 'img/addition.png' %}" alt="">
        </div>
        <div class="subtraction yurayura">
            <img src="{% static 'img/subtraction.png' %}" alt="">
        </div>
        <div class ="multiplication fuwafuwa">
            <img src="{% static 'img/multiplication.png' %}" alt="">
        </div>
        <div class="division fuwafuwa">
            <img src="{% static 'img/division.png' %}" alt="">
        </div>
        <div class="start-cat">
            <img src="{% static 'img/cat_start.png' %}" alt="ボタン上の猫">
        </div>
        <div class="start-btn d-flex">
        <a href="" class="btn btn--start btn--radius">はじめる！！</a>
        </div>
        <div class="bottom-cloud">
            <img src="{% static 'img/bottomCloud.png' %}" alt="雲">
        </div>
    </main>
{% endblock %}

survey/templates/index.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/ress.css' %}">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

    <!-- font -->
    <script>
        (function(d) {
          var config = {
            kitId: 'mvu8gqv',
            scriptTimeout: 3000,
            async: true
          },
          h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
        })(document);
    </script>

    <title>けいさんもんだい｜小学生の算数演習</title>
</head>
<body>
    <div class="top d-flex">
        <!-- 共通部分 -->
        <nav class="g-nav">
            <div class="logo">
                <a href="{% url 'survey:index' %}">
                    <img src="{% static 'img/logo.png' %}" alt="ロゴ" class="nav-logo">
                </a>
            </div>
            <ul>
                <li tabindex="1" class="grade">
                    <a href="{% url 'survey:grade1' %}">小学1年生</a>
                </li>
                <li tabindex="2" class="grade">
                    <a href="{% url 'survey:grade2' %}">小学2年生</a>
                </li>
                <li tabindex="3" class="grade grade3">
                    <a href="{% url 'survey:grade3' %}">小学3年生</a>
                </li> 
            </ul>
        </nav> <!-- 共通部分 -->
        <!-- トップページ -->
        <main class="top-page">
            <div class="top-logo d-flex">
                <img src="{% static 'img/logo.png' %}" alt="ロゴ">
            </div>
            <div class="left-cloud d-flex">
                <img src="{% static 'img/leftCloud.png' %}" alt="雲">
            </div>
            <div class="right-cloud d-flex">
                <img src="{% static 'img/rightCloud.png' %}" alt="雲">
            </div>
            <div class="top-cat d-flex">
                <img src="{% static 'img/cat_top.png' %}" alt="挑戦状と猫">
            </div>
            <div class="addition yurayura">
                <img src="{% static 'img/addition.png' %}" alt="">
            </div>
            <div class="subtraction yurayura">
                <img src="{% static 'img/subtraction.png' %}" alt="">
            </div>
            <div class ="multiplication fuwafuwa">
                <img src="{% static 'img/multiplication.png' %}" alt="">
            </div>
            <div class="division fuwafuwa">
                <img src="{% static 'img/division.png' %}" alt="">
            </div>
        </main>
    </div>
    
</body>
</html>

survey/templates/score100.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

    <main class="score100">
        <!-- アニメーション -->
        <div class="confetti"><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
        </div><!-- /アニメーション -->
        <p class="feedback">
            ぜんもんせいかい！！<br>
            キミはてんさいだ！！！
        </p>
        <div class="cat100">
            <img src="{% static 'img/cat100.png' %} alt="キラキラ猫">
        </div>
        <a href="" class="btn btn--orange btn--radius">もう一回する&emsp;<span class="c-font">&rarr;</span></a>
    </main>
    
{% endblock %}

survey/templates/score30-0.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="css/ress.css">
    <link rel="stylesheet" href="css/style.css">

    <!-- favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <script>
        (function(d) {
          var config = {
            kitId: 'mvu8gqv',
            scriptTimeout: 3000,
            async: true
          },
          h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
        })(document);
    </script>

    <title>けいさんもんだい｜小学生の算数演習</title>
</head>
<body class="d-flex">
    <!-- 共通部分 -->
    <nav class="g-nav">
        <div class="logo">
            <a href="index.html">
                <img src="images/logo.png" alt="ロゴ" class="nav-logo">
            </a>
        </div>
        <ul>
            <li tabindex="1" class="grade">
                <a href="grade2.html">小学1年生</a>
            </li>
            <li tabindex="2" class="grade">
                <a href="grade2.html">小学2年生</a>
            </li>
            <li tabindex="3" class="grade grade3">
                <a href="grade3.html">小学3年生</a>
            </li>
        </ul>
    </nav> <!-- 共通部分 -->
    <main class="score100">
        <!-- アニメーション -->
        <div class="confetti"><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
        </div><!-- /アニメーション -->
        <div class="score-result d-flex">
            <p class="score"><span class="red">100</span>/100</p>
        </div>
        <div class="feedback d-flex">
            <p class="feedback-txt">
                ぜんもんせいかい！！<br>
                キミはてんさいだ！！！
            </p>
        </div>
        <div class="cat100 d-flex">
            <img src="images/cat100.png" alt="キラキラ猫">
        </div>
        <a href="grade1.html" class="btn btn--orange btn--radius ">もう一回する&emsp;<span class="c-font">&rarr;</span></a>
    </main>
    
</body>
</html>

survey/templates/score60-40.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="css/ress.css">
    <link rel="stylesheet" href="css/style.css">

    <!-- favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <script>
        (function(d) {
          var config = {
            kitId: 'mvu8gqv',
            scriptTimeout: 3000,
            async: true
          },
          h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
        })(document);
    </script>

    <title>けいさんもんだい｜小学生の算数演習</title>
</head>
<body class="d-flex">
    <!-- 共通部分 -->
    <nav class="g-nav">
        <div class="logo">
            <a href="index.html">
                <img src="images/logo.png" alt="ロゴ" class="nav-logo">
            </a>
        </div>
        <ul>
            <li tabindex="1" class="grade">
                <a href="grade2.html">小学1年生</a>
            </li>
            <li tabindex="2" class="grade">
                <a href="grade2.html">小学2年生</a>
            </li>
            <li tabindex="3" class="grade grade3">
                <a href="grade3.html">小学3年生</a>
            </li>
        </ul>
    </nav> <!-- 共通部分 -->
    <main class="score100">
        <!-- アニメーション -->
        <div class="confetti"><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
        </div><!-- /アニメーション -->
        <div class="score-result d-flex">
            <p class="score"><span class="red">100</span>/100</p>
        </div>
        <div class="feedback d-flex">
            <p class="feedback-txt">
                ぜんもんせいかい！！<br>
                キミはてんさいだ！！！
            </p>
        </div>
        <div class="cat100 d-flex">
            <img src="images/cat100.png" alt="キラキラ猫">
        </div>
        <a href="grade1.html" class="btn btn--orange btn--radius ">もう一回する&emsp;<span class="c-font">&rarr;</span></a>
    </main>
    
</body>
</html>

survey/templates/score90-70.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="css/ress.css">
    <link rel="stylesheet" href="css/style.css">

    <!-- favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <script>
        (function(d) {
          var config = {
            kitId: 'mvu8gqv',
            scriptTimeout: 3000,
            async: true
          },
          h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
        })(document);
    </script>

    <title>けいさんもんだい｜小学生の算数演習</title>
</head>
<body class="d-flex">
    <!-- 共通部分 -->
    <nav class="g-nav">
        <div class="logo">
            <a href="index.html">
                <img src="images/logo.png" alt="ロゴ" class="nav-logo">
            </a>
        </div>
        <ul>
            <li tabindex="1" class="grade">
                <a href="grade2.html">小学1年生</a>
            </li>
            <li tabindex="2" class="grade">
                <a href="grade2.html">小学2年生</a>
            </li>
            <li tabindex="3" class="grade grade3">
                <a href="grade3.html">小学3年生</a>
            </li>
        </ul>
    </nav> <!-- 共通部分 -->
    <main class="score100">
        <!-- アニメーション -->
        <div class="confetti"><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
        </div><!-- /アニメーション -->
        <div class="score-result d-flex">
            <p class="score"><span class="red">100</span>/100</p>
        </div>
        <div class="feedback d-flex">
            <p class="feedback-txt">
                ぜんもんせいかい！！<br>
                キミはてんさいだ！！！
            </p>
        </div>
        <div class="cat100 d-flex">
            <img src="images/cat100.png" alt="キラキラ猫">
        </div>
        <a href="grade1.html" class="btn btn--orange btn--radius ">もう一回する&emsp;<span class="c-font">&rarr;</span></a>
    </main>
    
</body>
</html>